#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : keystonemiddleware
Version  : 5.2.0
Release  : 45
URL      : http://tarballs.openstack.org/keystonemiddleware/keystonemiddleware-5.2.0.tar.gz
Source0  : http://tarballs.openstack.org/keystonemiddleware/keystonemiddleware-5.2.0.tar.gz
Source99 : http://tarballs.openstack.org/keystonemiddleware/keystonemiddleware-5.2.0.tar.gz.asc
Summary  : Middleware for OpenStack Identity
Group    : Development/Tools
License  : Apache-2.0
Requires: keystonemiddleware-python3
Requires: keystonemiddleware-license
Requires: keystonemiddleware-python
Requires: Sphinx
Requires: WebOb
Requires: WebTest
Requires: bandit
Requires: coverage
Requires: cryptography
Requires: doc8
Requires: fixtures
Requires: flake8-docstrings
Requires: hacking
Requires: keystoneauth1
Requires: oslo.cache
Requires: oslo.config
Requires: oslo.context
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.messaging
Requires: oslo.serialization
Requires: oslo.utils
Requires: oslotest
Requires: pbr
Requires: pycadf
Requires: python-keystoneclient
Requires: python-memcached
Requires: python-mock
Requires: reno
Requires: requests
Requires: requests-mock
Requires: six
Requires: stevedore
Requires: testresources
Requires: testtools
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Team and repository tags
        ========================

%package license
Summary: license components for the keystonemiddleware package.
Group: Default

%description license
license components for the keystonemiddleware package.


%package python
Summary: python components for the keystonemiddleware package.
Group: Default
Requires: keystonemiddleware-python3

%description python
python components for the keystonemiddleware package.


%package python3
Summary: python3 components for the keystonemiddleware package.
Group: Default
Requires: python3-core

%description python3
python3 components for the keystonemiddleware package.


%prep
%setup -q -n keystonemiddleware-5.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532270325
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/keystonemiddleware
cp LICENSE %{buildroot}/usr/share/doc/keystonemiddleware/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/keystonemiddleware/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
