#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : keystonemiddleware
Version  : 4.10.0
Release  : 42
URL      : http://tarballs.openstack.org/keystonemiddleware/keystonemiddleware-4.10.0.tar.gz
Source0  : http://tarballs.openstack.org/keystonemiddleware/keystonemiddleware-4.10.0.tar.gz
Source99 : http://tarballs.openstack.org/keystonemiddleware/keystonemiddleware-4.10.0.tar.gz.asc
Summary  : Middleware for OpenStack Identity
Group    : Development/Tools
License  : Apache-2.0
Requires: keystonemiddleware-python
Requires: WebOb
Requires: keystoneauth1
Requires: oslo.config
Requires: oslo.context
Requires: oslo.i18n
Requires: oslo.messaging
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: positional
Requires: pycadf
Requires: python-keystoneclient
Requires: requests
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Middleware for the OpenStack Identity API (Keystone)
====================================================

%package python
Summary: python components for the keystonemiddleware package.
Group: Default

%description python
python components for the keystonemiddleware package.


%prep
%setup -q -n keystonemiddleware-4.10.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489271438
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489271438
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
